### ISSUE TITLE
swift 2 - would love to revive this project. 

### ISSUE THREAD

**Issue by johndpope** [jpsim/SwiftEdit#2]
any chance you can spend a day to knock it back into shape?

![screen shot 2015-08-19 at 1 28 42 pm](https://cloud.githubusercontent.com/assets/289994/9348160/3a893b58-4676-11e5-8375-a7e80ef27daa.png)

**Comment by jpsim** [comment]
The screenshot is a nice touch! Demonstrates how Xcode treats code that was compiling without warnings about 12 months prior. I just pushed an update for Xcode 7 Beta 5 to the master branch, just for you.

**Comment by johndpope** [comment]
thanks
